import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import {
  Outlet,
  Link,
  createRootRouteWithContext,
  useRouter,
  HeadContent,
  Scripts,
} from "@tanstack/react-router";
import { type ReactNode } from "react";

import appCss from "../styles.css?url";

import { SiteHeader } from "@/components/layout/SiteHeader";
import { SiteFooter } from "@/components/layout/SiteFooter";
import { CommerceProvider } from "@/lib/commerce-store";
import { Toaster } from "@/components/ui/sonner";
import { SupportProvider } from "@/components/support/support-context";
import { FloatingSupport } from "@/components/support/FloatingSupport";
import { SalesTrendPopups } from "@/components/shop/SalesTrendPopups";

import { SITE } from "@/config/site";
import { SITE_URL } from "@/config/seo";

const ROOT_TITLE = "Cossa Store | Project Commerce & Business Procurement";
const ROOT_DESCRIPTION =
  "Shop products, project solutions and business procurement through Cossa Store — a South African hybrid e-commerce and project-commerce platform operated by Cossa Nexus Holdings (Pty) Ltd.";

function NotFoundComponent() {
  return (
    <div className="flex min-h-screen items-center justify-center bg-background px-4">
      <div className="max-w-md text-center">
        <h1 className="text-7xl font-bold text-foreground">404</h1>

        <h2 className="mt-4 text-xl font-semibold text-foreground">
          Page not found
        </h2>

        <p className="mt-2 text-sm text-muted-foreground">
          The page you&apos;re looking for doesn&apos;t exist or may have moved.
        </p>

        <div className="mt-6">
          <Link
            to="/"
            className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90"
          >
            Go to Cossa Store
          </Link>
        </div>
      </div>
    </div>
  );
}

function ErrorComponent({
  error,
  reset,
}: {
  error: Error;
  reset: () => void;
}) {
  const router = useRouter();

  console.error("Cossa Store application error:", error);

  return (
    <div className="flex min-h-screen items-center justify-center bg-background px-4">
      <div className="max-w-md text-center">
        <h1 className="text-xl font-semibold tracking-tight text-foreground">
          This page didn&apos;t load
        </h1>

        <p className="mt-2 text-sm text-muted-foreground">
          Something went wrong while loading this page. You can try again or
          return to Cossa Store.
        </p>

        <div className="mt-6 flex flex-wrap justify-center gap-2">
          <button
            type="button"
            onClick={() => {
              router.invalidate();
              reset();
            }}
            className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90"
          >
            Try again
          </button>

          <Link
            to="/"
            className="inline-flex items-center justify-center rounded-md border border-input bg-background px-4 py-2 text-sm font-medium text-foreground transition-colors hover:bg-accent"
          >
            Go to Cossa Store
          </Link>
        </div>
      </div>
    </div>
  );
}

/**
 * Root-level structured data.
 *
 * This graph establishes:
 * 1. Cossa Store as the public online-store entity.
 * 2. Cossa Nexus Holdings (Pty) Ltd as the legal parent/operator.
 * 3. The relationship between the Store and its permanent website.
 *
 * Product-, breadcrumb-, category- and project-specific schema should
 * be generated by the relevant routes rather than being placed here.
 */
const ROOT_STRUCTURED_DATA = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "OnlineStore",
      "@id": SITE.structuredDataId,

      name: SITE.name,
      alternateName: SITE.alternateNames,

      url: SITE_URL,

      description: SITE.description,

      email: SITE.email,
      telephone: SITE.phoneInternational,

      currenciesAccepted: SITE.currency,

      areaServed: {
        "@type": "Country",
        name: SITE.country,
      },

      address: {
        "@type": "PostalAddress",
        addressLocality: "Centurion",
        addressRegion: "Gauteng",
        addressCountry: SITE.countryCode,
      },

      sameAs: [SITE.social.instagram, SITE.social.facebook],

      parentOrganization: {
        "@id": SITE.parentStructuredDataId,
      },

      contactPoint: [
        {
          "@type": "ContactPoint",
          telephone: SITE.phoneInternational,
          email: SITE.email,
          contactType: "customer service",
          areaServed: SITE.countryCode,
          availableLanguage: ["English"],
        },
      ],
    },

    {
      "@type": "Organization",
      "@id": SITE.parentStructuredDataId,

      name: SITE.parent,

      url: SITE.corporateWebsite,

      email: SITE.email,
      telephone: SITE.phoneInternational,

      identifier: {
        "@type": "PropertyValue",
        propertyID: "CIPC Registration Number",
        value: SITE.registrationNumber,
      },

      address: {
        "@type": "PostalAddress",
        addressLocality: "Centurion",
        addressRegion: "Gauteng",
        addressCountry: SITE.countryCode,
      },

      sameAs: [
        SITE.parentSocial.instagram,
        SITE.parentSocial.facebook,
        SITE.parentSocial.x,
        SITE.parentSocial.tiktok,
      ],
    },

    {
      "@type": "WebSite",
      "@id": `${SITE_URL}/#website`,

      name: SITE.name,
      alternateName: SITE.alternateNames,

      url: SITE_URL,

      description: SITE.description,

      publisher: {
        "@id": SITE.structuredDataId,
      },

      inLanguage: "en-ZA",
    },
  ],
};

export const Route = createRootRouteWithContext<{
  queryClient: QueryClient;
}>()({
  head: () => ({
    meta: [
      {
        charSet: "utf-8",
      },

      {
        name: "viewport",
        content: "width=device-width, initial-scale=1",
      },

      {
        title: ROOT_TITLE,
      },

      {
        name: "description",
        content: ROOT_DESCRIPTION,
      },

      {
        name: "author",
        content: SITE.parent,
      },

      {
        name: "application-name",
        content: SITE.name,
      },

      {
        name: "theme-color",
        content: "#000000",
      },

      /*
       * Open Graph
       */
      {
        property: "og:type",
        content: "website",
      },

      {
        property: "og:site_name",
        content: SITE.name,
      },

      {
        property: "og:title",
        content: ROOT_TITLE,
      },

      {
        property: "og:description",
        content: ROOT_DESCRIPTION,
      },

      {
        property: "og:url",
        content: SITE_URL,
      },

      {
        property: "og:locale",
        content: "en_ZA",
      },

      /*
       * X / Twitter card metadata.
       *
       * We deliberately do not claim a Store X account because
       * the Store currently uses Facebook and Instagram as its
       * confirmed primary social channels.
       */
      {
        name: "twitter:card",
        content: "summary_large_image",
      },

      {
        name: "twitter:title",
        content: ROOT_TITLE,
      },

      {
        name: "twitter:description",
        content: ROOT_DESCRIPTION,
      },

      /*
       * Search-engine locale / market hint.
       */
      {
        name: "geo.region",
        content: "ZA-GP",
      },

      {
        name: "geo.placename",
        content: "Centurion, Gauteng, South Africa",
      },
    ],

    links: [
      {
        rel: "stylesheet",
        href: appCss,
      },

      /*
       * Root canonical.
       *
       * Child routes already provide their own canonicals where
       * implemented and should continue doing so.
       */
      {
        rel: "canonical",
        href: SITE_URL,
      },

      {
        rel: "preconnect",
        href: "https://fonts.googleapis.com",
      },

      {
        rel: "preconnect",
        href: "https://fonts.gstatic.com",
        crossOrigin: "anonymous",
      },

      {
        rel: "stylesheet",
        href: "https://fonts.googleapis.com/css2?family=Archivo:wght@600;700;800&family=Inter:wght@400;500;600;700&display=swap",
      },

      {
        rel: "icon",
        href: "/favicon.png",
        type: "image/png",
      },
    ],

    scripts: [
      {
        type: "application/ld+json",
        children: JSON.stringify(ROOT_STRUCTURED_DATA),
      },
    ],
  }),

  shellComponent: RootShell,
  component: RootComponent,

  notFoundComponent: NotFoundComponent,
  errorComponent: ErrorComponent,
});

function RootShell({ children }: { children: ReactNode }) {
  return (
    <html lang="en-ZA">
      <head>
        <HeadContent />
      </head>

      <body>
        {children}
        <Scripts />
      </body>
    </html>
  );
}

function RootComponent() {
  const { queryClient } = Route.useRouteContext();

  return (
    <QueryClientProvider client={queryClient}>
      <CommerceProvider>
        <SupportProvider>
          <div className="flex min-h-dvh flex-col">
            <SiteHeader />

            <main className="flex-1">
              {/*
               * Nested TanStack Router routes render here.
               * Removing <Outlet /> breaks all child routes.
               */}
              <Outlet />
            </main>

            <SiteFooter />
          </div>

          {/*
           * Customer support layer.
           *
           * This will later evolve into the shared Cossa AI
           * Customer Support entry point connected to Growth,
           * live Store catalogue data and central customer context.
           */}
          <FloatingSupport />

          <SalesTrendPopups />

          <Toaster position="top-right" />
        </SupportProvider>
      </CommerceProvider>
    </QueryClientProvider>
  );
}
