import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const ORG_ID = "00000000-0000-4000-8000-000000000001";
const CJ_API_BASE = "https://developers.cjdropshipping.com/api2.0/v1";
const BALANCE_SAFETY_MULTIPLIER = 1.05;

type AdminClient = ReturnType<typeof createClient>;
type Address = { address1:string; address2:string; city:string; region:string; zip:string; country:string };
type CjLine = { orderItemId:string; productId:string; vid:string; quantity:number; sourceCostUsd:number };
type Freight = { origin:string; logisticName:string; shippingUsd:number; aging:string };

function defaultApiKey(name:string):string|undefined{const raw=Deno.env.get(name);if(!raw)return undefined;try{const v=JSON.parse(raw) as Record<string,unknown>;return typeof v.default==="string"&&v.default?v.default:undefined}catch{return undefined}}
function isNewKey(v:string){return v.startsWith("sb_secret_")||v.startsWith("sb_publishable_")}
function createSupabaseFetch(apiKey:string):typeof fetch{return(input,init)=>{const headers=new Headers(input instanceof Request?input.headers:undefined);if(init?.headers)new Headers(init.headers).forEach((value,key)=>headers.set(key,value));if(isNewKey(apiKey)&&headers.get("authorization")===`Bearer ${apiKey}`)headers.delete("authorization");headers.set("apikey",apiKey);return fetch(input,{...init,headers})}}
function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"}})}
function text(v:unknown,max=500){return typeof v==="string"?v.trim().slice(0,max):""}
function positive(v:unknown){const n=Number(v);return Number.isFinite(n)&&n>0?n:null}

async function cjToken(apiKey:string){const r=await fetch(`${CJ_API_BASE}/authentication/getAccessToken`,{method:"POST",headers:{"Content-Type":"application/json",Accept:"application/json"},body:JSON.stringify({apiKey})});const p=await r.json().catch(()=>null) as any;const token=p?.data?.accessToken;if(!r.ok||p?.code!==200||typeof token!=="string"||!token)throw new Error("cj_authentication_failed");return token}
async function cjGet(path:string,token:string){const r=await fetch(`${CJ_API_BASE}${path}`,{headers:{Accept:"application/json","CJ-Access-Token":token}});const p=await r.json().catch(()=>null) as any;if(!r.ok||p?.code!==200||p?.result===false)throw new Error("cj_request_failed");return p}
async function cjPost(path:string,token:string,body:unknown){const r=await fetch(`${CJ_API_BASE}${path}`,{method:"POST",headers:{Accept:"application/json","Content-Type":"application/json","CJ-Access-Token":token,platformToken:""},body:JSON.stringify(body)});const p=await r.json().catch(()=>null) as any;if(!r.ok||p?.code!==200||p?.result===false)throw new Error(`cj_request_failed_${p?.code??r.status}`);return p}
function readAddress(value:unknown):Address|null{if(!value||typeof value!=="object")return null;const r=value as Record<string,unknown>;const address1=text(r.address1,500),address2=text(r.address2,500),city=text(r.city,50),region=text(r.region,50),zip=text(r.zip,20),country=text(r.country,2).toUpperCase();if(!address1||!city||!region||!zip||country!=="ZA")return null;return{address1,address2,city,region,zip,country}}
function freightOptions(payload:any,origin:string):Freight[]{const rows=Array.isArray(payload?.data)?payload.data:[];return rows.map((r:any)=>({origin,logisticName:text(r?.logisticName,50),shippingUsd:positive(r?.totalPostageFee)??positive(r?.logisticPrice)??0,aging:text(r?.logisticAging,50)})).filter((x:Freight)=>x.logisticName&&x.shippingUsd>0)}
function maxDays(aging:string){const nums=aging.match(/\d+/g)?.map(Number).filter(Number.isFinite)??[];return nums.length?Math.max(...nums):999}
async function quoteCart(token:string,lines:CjLine[]):Promise<Freight|null>{const all:Freight[]=[];for(const origin of["CN","US"]){try{const p=await cjPost("/logistic/freightCalculate",token,{startCountryCode:origin,endCountryCode:"ZA",products:lines.map(l=>({vid:l.vid,quantity:l.quantity}))});all.push(...freightOptions(p,origin))}catch{}}if(!all.length)return null;all.sort((a,b)=>{const ad=maxDays(a.aging),bd=maxDays(b.aging);const aa=ad<=30?0:1,ba=bd<=30?0:1;if(aa!==ba)return aa-ba;if(ad!==bd)return ad-bd;return a.shippingUsd-b.shippingUsd});return all[0]}
async function mark(admin:AdminClient,storeOrderId:string,patch:Record<string,unknown>){const{error}=await admin.from("supplier_fulfilment_orders").update({...patch,updated_at:new Date().toISOString()}).eq("store_order_id",storeOrderId).eq("supplier","CJ Dropshipping");if(error)throw error}

Deno.serve(async(req)=>{
 if(req.method!=="POST")return json({error:"Method not allowed."},405);
 const supabaseUrl=Deno.env.get("SUPABASE_URL");const serviceKey=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??defaultApiKey("SUPABASE_SECRET_KEYS");const cjApiKey=Deno.env.get("CJ_API_KEY");if(!supabaseUrl||!serviceKey||!cjApiKey)return json({error:"Supplier fulfilment is not configured."},503);
 const admin=createClient(supabaseUrl,serviceKey,{global:{fetch:createSupabaseFetch(serviceKey)},auth:{autoRefreshToken:false,persistSession:false}});
 const body=await req.json().catch(()=>({})) as Record<string,unknown>;const storeOrderId=text(body.storeOrderId,64);const suppliedReference=text(body.paymentReference,200);if(!/^[0-9a-f-]{36}$/i.test(storeOrderId))return json({error:"Invalid store order."},400);
 const{data:order,error:orderError}=await admin.from("store_orders").select("id,organisation_id,order_number,status,payment_reference,customer_name,customer_email,customer_phone,metadata,store_order_items(id,product_id,quantity,metadata)").eq("id",storeOrderId).eq("organisation_id",ORG_ID).maybeSingle();if(orderError||!order)return json({error:"Store order not found."},404);if(order.status!=="paid")return json({error:"Only paid Store orders can be sent to CJ."},409);
 const internal=req.headers.get("x-cossa-internal-key");const trustedInternal=Boolean(internal&&internal===serviceKey);const trustedPaidTrigger=Boolean(suppliedReference&&order.payment_reference&&suppliedReference===order.payment_reference);if(!trustedInternal&&!trustedPaidTrigger)return json({error:"Fulfilment authorization required."},401);
 const address=readAddress((order.metadata as any)?.shipping_address);if(!address)return json({error:"Paid order has no valid South African delivery address."},422);
 const itemRows=Array.isArray(order.store_order_items)?order.store_order_items:[];const cjItems=itemRows.filter((i:any)=>i?.metadata?.provider==="CJ Dropshipping");if(!cjItems.length)return json({status:"not_required",supplier:"CJ Dropshipping"});
 const existing=await admin.from("supplier_fulfilment_orders").select("*").eq("store_order_id",storeOrderId).eq("supplier","CJ Dropshipping").maybeSingle();if(existing.error)return json({error:"Fulfilment state unavailable."},500);if(existing.data&&["submitted","paid","processing","shipped","delivered","action_required"].includes(existing.data.status))return json({status:existing.data.status,supplierOrderId:existing.data.supplier_order_id,idempotent:true,paymentActionRequired:existing.data.status==="action_required"});
 if(!existing.data){const inserted=await admin.from("supplier_fulfilment_orders").insert({organisation_id:ORG_ID,store_order_id:storeOrderId,supplier:"CJ Dropshipping",status:"creating",payment_status:"pending"});if(inserted.error)return json({error:"Could not reserve supplier fulfilment."},500)}else await mark(admin,storeOrderId,{status:"creating",last_error:null});
 try{
  const productIds=[...new Set(cjItems.map((i:any)=>i.product_id).filter(Boolean))];const{data:products,error:pe}=await admin.from("store_products").select("id,supplier_product_ref").in("id",productIds).eq("supplier_name","CJ Dropshipping");if(pe)throw pe;const productMap=new Map((products??[]).map((p:any)=>[p.id,p.supplier_product_ref]));
  const variantIds=cjItems.map((i:any)=>i?.metadata?.variant_id).filter(Boolean);const{data:variants,error:ve}=await admin.from("store_product_variants").select("id,product_id,provider_variant_id,source_cost,source_price,is_available").in("id",variantIds).eq("provider","CJ Dropshipping");if(ve)throw ve;const vMap=new Map((variants??[]).map((v:any)=>[v.id,v]));
  const lines:CjLine[]=cjItems.map((item:any)=>{const variant=vMap.get(item?.metadata?.variant_id);if(!variant||!variant.is_available)throw new Error("cj_variant_unavailable");const pid=productMap.get(item.product_id);if(!pid)throw new Error("cj_product_mapping_missing");const cost=positive(variant.source_cost)??positive(variant.source_price);if(!cost)throw new Error("cj_cost_missing");return{orderItemId:item.id,productId:String(pid),vid:String(variant.provider_variant_id),quantity:Number(item.quantity),sourceCostUsd:cost}});
  const token=await cjToken(cjApiKey);const freight=await quoteCart(token,lines);if(!freight)throw new Error("cj_no_za_logistics");const productCost=lines.reduce((s,l)=>s+l.sourceCostUsd*l.quantity,0);const estimatedTotal=productCost+freight.shippingUsd;const balancePayload=await cjGet("/shopping/pay/getBalance",token);const balance=Number(balancePayload?.data?.amount??0);const payType=balance>=estimatedTotal*BALANCE_SAFETY_MULTIPLIER?2:1;
  const requestPayload={orderNumber:order.order_number,shippingZip:address.zip,shippingCountry:"South Africa",shippingCountryCode:"ZA",shippingProvince:address.region,shippingCity:address.city,shippingCounty:"",shippingPhone:text(order.customer_phone,20),shippingCustomerName:text(order.customer_name,50),shippingAddress:address.address1,shippingAddress2:address.address2,email:text(order.customer_email,50),remark:`Cossa Store ${order.order_number}`,payType,logisticName:freight.logisticName,fromCountryCode:freight.origin,platform:"Api",orderFlow:1,products:lines.map(l=>({vid:l.vid,quantity:l.quantity,storeLineItemId:l.orderItemId}))};
  await mark(admin,storeOrderId,{logistics_method:freight.logisticName,origin_country_code:freight.origin,destination_country_code:"ZA",supplier_cost_usd:Math.round(productCost*100)/100,shipping_cost_usd:Math.round(freight.shippingUsd*100)/100,total_supplier_cost_usd:Math.round(estimatedTotal*100)/100,request_payload:requestPayload});
  const created=await cjPost("/shopping/order/createOrderV2",token,requestPayload);const d=created?.data??{};const orderId=text(d.orderId??d.shipmentOrderId,200);const paymentUrl=text(d.cjPayUrl,500);const actual=positive(d.actualPayment)??positive(d.orderAmount)??estimatedTotal;const intercepts=Array.isArray(d.interceptOrderReasons)?d.interceptOrderReasons:[];const blocked=Boolean(d.logisticsMiss)||intercepts.length>0;const paid=payType===2&&!paymentUrl&&!blocked;const finalStatus=blocked?"action_required":paid?"paid":paymentUrl?"action_required":"submitted";const paymentStatus=paid?"paid":finalStatus==="action_required"?"action_required":"pending";
  await mark(admin,storeOrderId,{supplier_order_id:orderId||null,supplier_order_number:text(d.orderNumber,200)||null,status:finalStatus,payment_status:paymentStatus,payment_url:paymentUrl||null,total_supplier_cost_usd:Math.round(actual*100)/100,response_payload:{orderId:orderId||null,orderNumber:text(d.orderNumber,200)||null,shipmentOrderId:text(d.shipmentOrderId,200)||null,orderStatus:text(d.orderStatus,50)||null,logisticsMiss:Boolean(d.logisticsMiss),interceptOrderReasons:intercepts,hasPaymentUrl:Boolean(paymentUrl)},last_error:blocked?"CJ returned an order interception or logistics exception.":null});
  return json({status:finalStatus,supplier:"CJ Dropshipping",supplierOrderId:orderId||null,balancePaymentUsed:payType===2,paymentActionRequired:finalStatus==="action_required"});
 }catch(error){const message=error instanceof Error?error.message:"supplier_fulfilment_failed";try{await mark(admin,storeOrderId,{status:"failed",payment_status:"failed",last_error:message.slice(0,500)})}catch{}return json({error:"CJ fulfilment could not be completed automatically.",status:"failed"},502)}
});
