import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient, type User } from "https://esm.sh/@supabase/supabase-js@2";

const ORG_ID = "00000000-0000-4000-8000-000000000001";
const CJ_API_BASE = "https://developers.cjdropshipping.com/api2.0/v1";
const MAX_PRODUCTS = 6;
const REQUEST_GAP_MS = 1100;
const ALLOWED_ORIGINS = new Set(["https://store.cossanexusholdings.co.za","https://growth.cossanexusholdings.co.za","http://localhost:3000","http://localhost:5173"]);
type AdminClient=ReturnType<typeof createClient>;

function defaultApiKey(name:string){const raw=Deno.env.get(name);if(!raw)return undefined;try{const o=JSON.parse(raw) as Record<string,unknown>;return typeof o.default==="string"&&o.default?o.default:undefined}catch{return undefined}}
function newKey(v:string){return v.startsWith("sb_publishable_")||v.startsWith("sb_secret_")}
function sf(apiKey:string):typeof fetch{return(input,init)=>{const h=new Headers(input instanceof Request?input.headers:undefined);if(init?.headers)new Headers(init.headers).forEach((v,k)=>h.set(k,v));if(newKey(apiKey)&&h.get("authorization")===`Bearer ${apiKey}`)h.delete("authorization");h.set("apikey",apiKey);return fetch(input,{...init,headers:h})}}
function cors(req:Request):HeadersInit{const o=req.headers.get("origin");return{"Access-Control-Allow-Origin":o&&ALLOWED_ORIGINS.has(o)?o:"","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Access-Control-Allow-Credentials":"true",Vary:"Origin"}}
function json(req:Request,b:unknown,s=200){return new Response(JSON.stringify(b),{status:s,headers:{...cors(req),"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"}})}
function txt(v:unknown,m=500){return typeof v==="string"?v.replace(/\s+/g," ").trim().slice(0,m):""}
function id(v:unknown){const x=txt(v,200);return /^[A-Za-z0-9_-]{1,200}$/.test(x)?x:""}
function pos(v:unknown){const n=Number(v);return Number.isFinite(n)&&n>0?n:null}
function int0(v:unknown){const n=Number(v);return Number.isFinite(n)&&n>0?Math.floor(n):0}
function http(v:unknown):v is string{if(typeof v!=="string")return false;try{const u=new URL(v);return u.protocol==="https:"||u.protocol==="http:"}catch{return false}}
function slug(v:string){return v.toLowerCase().normalize("NFKD").replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").replace(/-{2,}/g,"-")}
function desc(v:unknown){return txt(txt(v,12000).replace(/<[^>]*>/g," ").replace(/&nbsp;/gi," ").replace(/&amp;/gi,"&"),12000)}
function category(v:unknown){const c=txt(v,500).toLowerCase();if(/pet/.test(c))return"pet-supplies";if(/clean|laundry|household cleaner/.test(c))return"cleaning-household";if(/tool|home improvement|construction|hardware|industrial/.test(c))return"construction-diy";if(/computer|consumer electronic|phone|mobile|electronic|camera/.test(c))return"technology-electronics";if(/men'?s clothing|\bmen\b/.test(c))return"men";if(/women'?s clothing|\bwomen\b/.test(c))return"women";if(/home|furniture|kitchen|bath|lighting|storage|bedding/.test(c))return"home-living";if(/garden|outdoor/.test(c))return"outdoor-garden";if(/sport|fitness/.test(c))return"sports-fitness";if(/baby|kids|toy/.test(c))return"kids-baby";return null}
async function user(req:Request,c:ReturnType<typeof createClient>):Promise<User>{const t=req.headers.get("authorization")?.replace(/^Bearer\s+/i,"").trim();if(!t)throw 0;const{data,error}=await c.auth.getUser(t);if(error||!data.user)throw 0;return data.user}
async function adminOk(a:AdminClient,u:string){const[m,r]=await Promise.all([a.from("organisation_members").select("role").eq("organisation_id",ORG_ID).eq("user_id",u).eq("status","active").in("role",["owner","admin"]),a.from("user_roles").select("role").eq("user_id",u).eq("role","admin")]);if(m.error||r.error||(!(m.data??[]).length&&!(r.data??[]).length))throw 0}
async function token(k:string){const r=await fetch(`${CJ_API_BASE}/authentication/getAccessToken`,{method:"POST",headers:{"Content-Type":"application/json",Accept:"application/json"},body:JSON.stringify({apiKey:k})});const p=await r.json().catch(()=>null) as any;const t=p?.data?.accessToken;if(!r.ok||p?.code!==200||!t)throw new Error("cj_authentication_failed");return String(t)}
function client(t:string){let last=0;return async(path:string)=>{const wait=REQUEST_GAP_MS-(Date.now()-last);if(wait>0)await new Promise(r=>setTimeout(r,wait));const r=await fetch(`${CJ_API_BASE}${path}`,{headers:{Accept:"application/json","CJ-Access-Token":t}});last=Date.now();const p=await r.json().catch(()=>null) as any;if(!r.ok||p?.code!==200)throw new Error("cj_request_failed");return p}}
function candidates(payload:any){const out:Array<{id:string;category:string}>=[];const seen=new Set<string>();const scan=(v:any)=>{if(Array.isArray(v)){v.forEach(scan);return}if(!v||typeof v!=="object")return;const pid=id(v.id)||id(v.pid);const cat=category(v.categoryName||[v.oneCategoryName,v.twoCategoryName,v.threeCategoryName].filter(Boolean).join(" / "));if(pid&&cat&&!seen.has(pid)){seen.add(pid);out.push({id:pid,category:cat})}Object.values(v).forEach(x=>{if(Array.isArray(x))scan(x)})};scan(payload?.data);const priority=["construction-diy","home-living","cleaning-household","technology-electronics","pet-supplies","women","men"];return out.sort((a,b)=>{const ai=priority.indexOf(a.category),bi=priority.indexOf(b.category);return (ai<0?999:ai)-(bi<0?999:bi)}).slice(0,MAX_PRODUCTS)}
function inv(v:any){return Array.isArray(v)?v.reduce((s:any,x:any)=>s+int0(x?.totalInventory??x?.totalInventoryNum),0):0}

Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors(req)});if(req.method!=="POST")return json(req,{error:"Method not allowed."},405);const o=req.headers.get("origin");if(o&&!ALLOWED_ORIGINS.has(o))return json(req,{error:"Origin not allowed."},403);
 const url=Deno.env.get("SUPABASE_URL"),pub=Deno.env.get("SUPABASE_PUBLISHABLE_KEY")??Deno.env.get("SUPABASE_ANON_KEY")??defaultApiKey("SUPABASE_PUBLISHABLE_KEYS"),srv=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??defaultApiKey("SUPABASE_SECRET_KEYS"),ck=Deno.env.get("CJ_API_KEY");if(!url||!pub||!srv||!ck)return json(req,{error:"CJ catalogue sync is not configured."},503);const uc=createClient(url,pub,{global:{fetch:sf(pub)},auth:{autoRefreshToken:false,persistSession:false}}),a=createClient(url,srv,{global:{fetch:sf(srv)},auth:{autoRefreshToken:false,persistSession:false}});let u:User;try{u=await user(req,uc);await adminOk(a,u.id)}catch{return json(req,{error:"An authorised Cossa Store administrator is required."},401)}
 try{const cj=client(await token(ck));const params=new URLSearchParams({page:"1",size:"30",productFlag:"0",startWarehouseInventory:"1",verifiedWarehouse:"1",orderBy:"1",sort:"desc"});params.append("features","enable_description");params.append("features","enable_category");const list=candidates(await cj(`/product/listV2?${params}`));const summary={requested:list.length,createdAsDraft:0,refreshed:0,skipped:0,products:[] as any[]};
  for(const c of list){try{const p=(await cj(`/product/query?pid=${encodeURIComponent(c.id)}`))?.data??{};const pid=id(p.pid),rawName=txt(p.productNameEn,220),full=desc(p.description),images=[p.bigImage,...(Array.isArray(p.productImageSet)?p.productImageSet:[])].filter(http).filter((x:string,i:number,a:string[])=>a.indexOf(x)===i).slice(0,12),vs=Array.isArray(p.variants)?p.variants:[],costs=vs.map((v:any)=>pos(v.variantSellPrice)).filter((x:any):x is number=>x!==null),cat=category(p.categoryName)??c.category;if(!pid||!rawName||!full||!images.length||!vs.length||!costs.length||!cat){summary.skipped++;continue}
   const ex=await a.from("store_products").select("id,slug,sku,status,name,short_description,description,category,brand,price,cost_price,seo_title,seo_description").eq("organisation_id",ORG_ID).eq("supplier_name","CJ Dropshipping").eq("supplier_product_ref",pid).maybeSingle();if(ex.error)throw ex.error;const old=ex.data as any;const active=old?.status==="active";const now=new Date().toISOString(),min=Math.min(...costs),total=vs.reduce((s:number,v:any)=>s+inv(v.inventories),0);const row={organisation_id:ORG_ID,name:active&&old.name?old.name:rawName,slug:old?.slug||`cj-${slug(rawName).slice(0,130)}-${pid.slice(0,8).toLowerCase()}`,sku:old?.sku||`CJ-${pid.replace(/[^A-Za-z0-9]/g,"").slice(0,16).toUpperCase()}`,product_type:"dropshipping",fulfilment_model:"international_dropshipping",status:old?.status==="active"?"active":old?.status==="archived"?"archived":"draft",short_description:active&&old.short_description?old.short_description:full.slice(0,240),description:active&&old.description?old.description:full,category:old?.category||cat,brand:old?.brand||"Cossa Store",supplier_name:"CJ Dropshipping",supplier_product_ref:pid,currency:"ZAR",source_currency:"USD",source_price:min,source_cost:min,cost_price:old?.cost_price??0,price:old?.price??0,track_inventory:true,stock_quantity:total,unlimited_stock:false,image_urls:images,seo_title:active&&old.seo_title?old.seo_title:rawName.slice(0,70),seo_description:active&&old.seo_description?old.seo_description:full.slice(0,160),updated_at:now};const saved=old?await a.from("store_products").update(row).eq("id",old.id).select("id").single():await a.from("store_products").insert(row).select("id").single();if(saved.error)throw saved.error;
   const cur=await a.from("store_product_variants").select("provider_variant_id,price_zar,cost_zar,fx_rate_to_zar").eq("product_id",saved.data.id).eq("provider","CJ Dropshipping");if(cur.error)throw cur.error;const prices=new Map((cur.data??[]).map((r:any)=>[r.provider_variant_id,r]));const rows=vs.map((v:any,i:number)=>{const vid=id(v.vid),source=pos(v.variantSellPrice);if(!vid||!source)return null;const prev=prices.get(vid) as any;return{product_id:saved.data.id,provider:"CJ Dropshipping",provider_product_id:pid,provider_variant_id:vid,sku:txt(v.variantSku,220)||null,title:txt(v.variantNameEn,220)||txt(v.variantKey,220)||`CJ option ${i+1}`,option_values:txt(v.variantKey,220)?[{name:"CJ option",value:txt(v.variantKey,220)}]:[],source_currency:"USD",source_price:source,source_cost:source,fx_rate_to_zar:prev?.fx_rate_to_zar??null,price_zar:prev?.price_zar??0,cost_zar:prev?.cost_zar??null,is_default:i===0,is_available:inv(v.inventories)>0,sort_order:i,raw_provider_data:{source:"CJ Dropshipping",weight_g:pos(v.variantWeight),inventory:Array.isArray(v.inventories)?v.inventories:[],variant:v},updated_at:now}}).filter(Boolean);if(!rows.length){summary.skipped++;continue}const up=await a.from("store_product_variants").upsert(rows,{onConflict:"product_id,provider,provider_variant_id"});if(up.error)throw up.error;summary[old?"refreshed":"createdAsDraft"]++;summary.products.push({productId:pid,title:row.name,variants:rows.length,availableVariants:rows.filter((r:any)=>r.is_available).length});
  }catch{summary.skipped++}}
  await a.from("audit_events").insert({organisation_id:ORG_ID,actor_type:"user",actor_user_id:u.id,event_type:"cj_catalogue_sync_succeeded",entity_type:"store_catalogue",entity_id:"cj_dropshipping",metadata:{requested:summary.requested,created_draft:summary.createdAsDraft,refreshed:summary.refreshed,skipped:summary.skipped}});return json(req,summary)
 }catch{return json(req,{error:"CJ catalogue sync is temporarily unavailable. No customer-facing catalogue data was changed."},502)}});
