/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BusinessAccountRouteImport } from './routes/business-account'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RequestAQuoteRouteImport } from './routes/request-a-quote'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ShopByProjectRouteImport } from './routes/shop-by-project'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SupplierApplicationRouteImport } from './routes/supplier-application'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as AccountOrdersRouteImport } from './routes/account.orders'
import { Route as AccountProjectsRouteImport } from './routes/account.projects'
import { Route as AccountWishlistRouteImport } from './routes/account.wishlist'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as DevCatalogueRouteImport } from './routes/dev.catalogue'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as ProjectSlugRouteImport } from './routes/project.$slug'
import { Route as AuthenticatedAdminApprovalsRouteImport } from './routes/_authenticated/admin.approvals'
import { Route as AuthenticatedAdminEmailOperationsRouteImport } from './routes/_authenticated/admin.email-operations'
import { Route as AuthenticatedAdminServicesRouteImport } from './routes/_authenticated/admin.services'
import { Route as AuthenticatedAdminCatalogueIndexRouteImport } from './routes/_authenticated/admin.catalogue.index'
import { Route as AuthenticatedAdminCatalogueIdRouteImport } from './routes/_authenticated/admin.catalogue.$id'
import { Route as AuthenticatedAdminCatalogueNewRouteImport } from './routes/_authenticated/admin.catalogue.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessAccountRoute = BusinessAccountRouteImport.update({
  id: '/business-account',
  path: '/business-account',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestAQuoteRoute = RequestAQuoteRouteImport.update({
  id: '/request-a-quote',
  path: '/request-a-quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopByProjectRoute = ShopByProjectRouteImport.update({
  id: '/shop-by-project',
  path: '/shop-by-project',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierApplicationRoute = SupplierApplicationRouteImport.update({
  id: '/supplier-application',
  path: '/supplier-application',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AccountRoute,
} as any)
const AccountProjectsRoute = AccountProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AccountRoute,
} as any)
const AccountWishlistRoute = AccountWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AccountRoute,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DevCatalogueRoute = DevCatalogueRouteImport.update({
  id: '/dev/catalogue',
  path: '/dev/catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectSlugRoute = ProjectSlugRouteImport.update({
  id: '/project/$slug',
  path: '/project/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminApprovalsRoute =
  AuthenticatedAdminApprovalsRouteImport.update({
    id: '/admin/approvals',
    path: '/admin/approvals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminEmailOperationsRoute =
  AuthenticatedAdminEmailOperationsRouteImport.update({
    id: '/admin/email-operations',
    path: '/admin/email-operations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminServicesRoute =
  AuthenticatedAdminServicesRouteImport.update({
    id: '/admin/services',
    path: '/admin/services',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCatalogueIndexRoute =
  AuthenticatedAdminCatalogueIndexRouteImport.update({
    id: '/admin/catalogue/',
    path: '/admin/catalogue/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCatalogueIdRoute =
  AuthenticatedAdminCatalogueIdRouteImport.update({
    id: '/admin/catalogue/$id',
    path: '/admin/catalogue/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCatalogueNewRoute =
  AuthenticatedAdminCatalogueNewRouteImport.update({
    id: '/admin/catalogue/new',
    path: '/admin/catalogue/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/auth': typeof AuthRoute
  '/business-account': typeof BusinessAccountRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/delivery': typeof DeliveryRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy': typeof PrivacyRoute
  '/request-a-quote': typeof RequestAQuoteRoute
  '/returns': typeof ReturnsRoute
  '/search': typeof SearchRoute
  '/shop': typeof ShopRoute
  '/shop-by-project': typeof ShopByProjectRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/supplier-application': typeof SupplierApplicationRoute
  '/terms': typeof TermsRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/projects': typeof AccountProjectsRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/category/$slug': typeof CategorySlugRoute
  '/dev/catalogue': typeof DevCatalogueRoute
  '/product/$slug': typeof ProductSlugRoute
  '/project/$slug': typeof ProjectSlugRoute
  '/account/': typeof AccountIndexRoute
  '/admin/approvals': typeof AuthenticatedAdminApprovalsRoute
  '/admin/email-operations': typeof AuthenticatedAdminEmailOperationsRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/catalogue/$id': typeof AuthenticatedAdminCatalogueIdRoute
  '/admin/catalogue/new': typeof AuthenticatedAdminCatalogueNewRoute
  '/admin/catalogue/': typeof AuthenticatedAdminCatalogueIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/business-account': typeof BusinessAccountRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/delivery': typeof DeliveryRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy': typeof PrivacyRoute
  '/request-a-quote': typeof RequestAQuoteRoute
  '/returns': typeof ReturnsRoute
  '/search': typeof SearchRoute
  '/shop': typeof ShopRoute
  '/shop-by-project': typeof ShopByProjectRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/supplier-application': typeof SupplierApplicationRoute
  '/terms': typeof TermsRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/projects': typeof AccountProjectsRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/category/$slug': typeof CategorySlugRoute
  '/dev/catalogue': typeof DevCatalogueRoute
  '/product/$slug': typeof ProductSlugRoute
  '/project/$slug': typeof ProjectSlugRoute
  '/account': typeof AccountIndexRoute
  '/admin/approvals': typeof AuthenticatedAdminApprovalsRoute
  '/admin/email-operations': typeof AuthenticatedAdminEmailOperationsRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/catalogue/$id': typeof AuthenticatedAdminCatalogueIdRoute
  '/admin/catalogue/new': typeof AuthenticatedAdminCatalogueNewRoute
  '/admin/catalogue': typeof AuthenticatedAdminCatalogueIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/auth': typeof AuthRoute
  '/business-account': typeof BusinessAccountRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/delivery': typeof DeliveryRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy': typeof PrivacyRoute
  '/request-a-quote': typeof RequestAQuoteRoute
  '/returns': typeof ReturnsRoute
  '/search': typeof SearchRoute
  '/shop': typeof ShopRoute
  '/shop-by-project': typeof ShopByProjectRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/supplier-application': typeof SupplierApplicationRoute
  '/terms': typeof TermsRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/projects': typeof AccountProjectsRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/category/$slug': typeof CategorySlugRoute
  '/dev/catalogue': typeof DevCatalogueRoute
  '/product/$slug': typeof ProductSlugRoute
  '/project/$slug': typeof ProjectSlugRoute
  '/account/': typeof AccountIndexRoute
  '/_authenticated/admin/approvals': typeof AuthenticatedAdminApprovalsRoute
  '/_authenticated/admin/email-operations': typeof AuthenticatedAdminEmailOperationsRoute
  '/_authenticated/admin/services': typeof AuthenticatedAdminServicesRoute
  '/_authenticated/admin/catalogue/$id': typeof AuthenticatedAdminCatalogueIdRoute
  '/_authenticated/admin/catalogue/new': typeof AuthenticatedAdminCatalogueNewRoute
  '/_authenticated/admin/catalogue/': typeof AuthenticatedAdminCatalogueIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/auth'
    | '/business-account'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/delivery'
    | '/how-it-works'
    | '/privacy'
    | '/request-a-quote'
    | '/returns'
    | '/search'
    | '/shop'
    | '/shop-by-project'
    | '/sitemap.xml'
    | '/supplier-application'
    | '/terms'
    | '/account/orders'
    | '/account/projects'
    | '/account/wishlist'
    | '/category/$slug'
    | '/dev/catalogue'
    | '/product/$slug'
    | '/project/$slug'
    | '/account/'
    | '/admin/approvals'
    | '/admin/email-operations'
    | '/admin/services'
    | '/admin/catalogue/$id'
    | '/admin/catalogue/new'
    | '/admin/catalogue/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/business-account'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/delivery'
    | '/how-it-works'
    | '/privacy'
    | '/request-a-quote'
    | '/returns'
    | '/search'
    | '/shop'
    | '/shop-by-project'
    | '/sitemap.xml'
    | '/supplier-application'
    | '/terms'
    | '/account/orders'
    | '/account/projects'
    | '/account/wishlist'
    | '/category/$slug'
    | '/dev/catalogue'
    | '/product/$slug'
    | '/project/$slug'
    | '/account'
    | '/admin/approvals'
    | '/admin/email-operations'
    | '/admin/services'
    | '/admin/catalogue/$id'
    | '/admin/catalogue/new'
    | '/admin/catalogue'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/account'
    | '/auth'
    | '/business-account'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/delivery'
    | '/how-it-works'
    | '/privacy'
    | '/request-a-quote'
    | '/returns'
    | '/search'
    | '/shop'
    | '/shop-by-project'
    | '/sitemap.xml'
    | '/supplier-application'
    | '/terms'
    | '/account/orders'
    | '/account/projects'
    | '/account/wishlist'
    | '/category/$slug'
    | '/dev/catalogue'
    | '/product/$slug'
    | '/project/$slug'
    | '/account/'
    | '/_authenticated/admin/approvals'
    | '/_authenticated/admin/email-operations'
    | '/_authenticated/admin/services'
    | '/_authenticated/admin/catalogue/$id'
    | '/_authenticated/admin/catalogue/new'
    | '/_authenticated/admin/catalogue/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRouteWithChildren
  AuthRoute: typeof AuthRoute
  BusinessAccountRoute: typeof BusinessAccountRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  DeliveryRoute: typeof DeliveryRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PrivacyRoute: typeof PrivacyRoute
  RequestAQuoteRoute: typeof RequestAQuoteRoute
  ReturnsRoute: typeof ReturnsRoute
  SearchRoute: typeof SearchRoute
  ShopRoute: typeof ShopRoute
  ShopByProjectRoute: typeof ShopByProjectRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupplierApplicationRoute: typeof SupplierApplicationRoute
  TermsRoute: typeof TermsRoute
  CategorySlugRoute: typeof CategorySlugRoute
  DevCatalogueRoute: typeof DevCatalogueRoute
  ProductSlugRoute: typeof ProductSlugRoute
  ProjectSlugRoute: typeof ProjectSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-account': {
      id: '/business-account'
      path: '/business-account'
      fullPath: '/business-account'
      preLoaderRoute: typeof BusinessAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-a-quote': {
      id: '/request-a-quote'
      path: '/request-a-quote'
      fullPath: '/request-a-quote'
      preLoaderRoute: typeof RequestAQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop-by-project': {
      id: '/shop-by-project'
      path: '/shop-by-project'
      fullPath: '/shop-by-project'
      preLoaderRoute: typeof ShopByProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier-application': {
      id: '/supplier-application'
      path: '/supplier-application'
      fullPath: '/supplier-application'
      preLoaderRoute: typeof SupplierApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/projects': {
      id: '/account/projects'
      path: '/projects'
      fullPath: '/account/projects'
      preLoaderRoute: typeof AccountProjectsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/wishlist': {
      id: '/account/wishlist'
      path: '/wishlist'
      fullPath: '/account/wishlist'
      preLoaderRoute: typeof AccountWishlistRouteImport
      parentRoute: typeof AccountRoute
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/catalogue': {
      id: '/dev/catalogue'
      path: '/dev/catalogue'
      fullPath: '/dev/catalogue'
      preLoaderRoute: typeof DevCatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$slug': {
      id: '/project/$slug'
      path: '/project/$slug'
      fullPath: '/project/$slug'
      preLoaderRoute: typeof ProjectSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/approvals': {
      id: '/_authenticated/admin/approvals'
      path: '/admin/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AuthenticatedAdminApprovalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/email-operations': {
      id: '/_authenticated/admin/email-operations'
      path: '/admin/email-operations'
      fullPath: '/admin/email-operations'
      preLoaderRoute: typeof AuthenticatedAdminEmailOperationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/services': {
      id: '/_authenticated/admin/services'
      path: '/admin/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AuthenticatedAdminServicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/catalogue/': {
      id: '/_authenticated/admin/catalogue/'
      path: '/admin/catalogue'
      fullPath: '/admin/catalogue/'
      preLoaderRoute: typeof AuthenticatedAdminCatalogueIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/catalogue/$id': {
      id: '/_authenticated/admin/catalogue/$id'
      path: '/admin/catalogue/$id'
      fullPath: '/admin/catalogue/$id'
      preLoaderRoute: typeof AuthenticatedAdminCatalogueIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/catalogue/new': {
      id: '/_authenticated/admin/catalogue/new'
      path: '/admin/catalogue/new'
      fullPath: '/admin/catalogue/new'
      preLoaderRoute: typeof AuthenticatedAdminCatalogueNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminApprovalsRoute: typeof AuthenticatedAdminApprovalsRoute
  AuthenticatedAdminEmailOperationsRoute: typeof AuthenticatedAdminEmailOperationsRoute
  AuthenticatedAdminServicesRoute: typeof AuthenticatedAdminServicesRoute
  AuthenticatedAdminCatalogueIdRoute: typeof AuthenticatedAdminCatalogueIdRoute
  AuthenticatedAdminCatalogueNewRoute: typeof AuthenticatedAdminCatalogueNewRoute
  AuthenticatedAdminCatalogueIndexRoute: typeof AuthenticatedAdminCatalogueIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminApprovalsRoute: AuthenticatedAdminApprovalsRoute,
  AuthenticatedAdminEmailOperationsRoute:
    AuthenticatedAdminEmailOperationsRoute,
  AuthenticatedAdminServicesRoute: AuthenticatedAdminServicesRoute,
  AuthenticatedAdminCatalogueIdRoute: AuthenticatedAdminCatalogueIdRoute,
  AuthenticatedAdminCatalogueNewRoute: AuthenticatedAdminCatalogueNewRoute,
  AuthenticatedAdminCatalogueIndexRoute: AuthenticatedAdminCatalogueIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AccountRouteChildren {
  AccountOrdersRoute: typeof AccountOrdersRoute
  AccountProjectsRoute: typeof AccountProjectsRoute
  AccountWishlistRoute: typeof AccountWishlistRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountOrdersRoute: AccountOrdersRoute,
  AccountProjectsRoute: AccountProjectsRoute,
  AccountWishlistRoute: AccountWishlistRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRouteWithChildren,
  AuthRoute: AuthRoute,
  BusinessAccountRoute: BusinessAccountRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  DeliveryRoute: DeliveryRoute,
  HowItWorksRoute: HowItWorksRoute,
  PrivacyRoute: PrivacyRoute,
  RequestAQuoteRoute: RequestAQuoteRoute,
  ReturnsRoute: ReturnsRoute,
  SearchRoute: SearchRoute,
  ShopRoute: ShopRoute,
  ShopByProjectRoute: ShopByProjectRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupplierApplicationRoute: SupplierApplicationRoute,
  TermsRoute: TermsRoute,
  CategorySlugRoute: CategorySlugRoute,
  DevCatalogueRoute: DevCatalogueRoute,
  ProductSlugRoute: ProductSlugRoute,
  ProjectSlugRoute: ProjectSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
