/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopByProjectRouteImport } from './routes/shop-by-project'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RequestAQuoteRouteImport } from './routes/request-a-quote'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BusinessAccountRouteImport } from './routes/business-account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectSlugRouteImport } from './routes/project.$slug'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'

const ShopByProjectRoute = ShopByProjectRouteImport.update({
  id: '/shop-by-project',
  path: '/shop-by-project',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestAQuoteRoute = RequestAQuoteRouteImport.update({
  id: '/request-a-quote',
  path: '/request-a-quote',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessAccountRoute = BusinessAccountRouteImport.update({
  id: '/business-account',
  path: '/business-account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectSlugRoute = ProjectSlugRouteImport.update({
  id: '/project/$slug',
  path: '/project/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/business-account': typeof BusinessAccountRoute
  '/cart': typeof CartRoute
  '/request-a-quote': typeof RequestAQuoteRoute
  '/search': typeof SearchRoute
  '/shop': typeof ShopRoute
  '/shop-by-project': typeof ShopByProjectRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/project/$slug': typeof ProjectSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/business-account': typeof BusinessAccountRoute
  '/cart': typeof CartRoute
  '/request-a-quote': typeof RequestAQuoteRoute
  '/search': typeof SearchRoute
  '/shop': typeof ShopRoute
  '/shop-by-project': typeof ShopByProjectRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/project/$slug': typeof ProjectSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/business-account': typeof BusinessAccountRoute
  '/cart': typeof CartRoute
  '/request-a-quote': typeof RequestAQuoteRoute
  '/search': typeof SearchRoute
  '/shop': typeof ShopRoute
  '/shop-by-project': typeof ShopByProjectRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/project/$slug': typeof ProjectSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/business-account'
    | '/cart'
    | '/request-a-quote'
    | '/search'
    | '/shop'
    | '/shop-by-project'
    | '/category/$slug'
    | '/product/$slug'
    | '/project/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/business-account'
    | '/cart'
    | '/request-a-quote'
    | '/search'
    | '/shop'
    | '/shop-by-project'
    | '/category/$slug'
    | '/product/$slug'
    | '/project/$slug'
  id:
    | '__root__'
    | '/'
    | '/business-account'
    | '/cart'
    | '/request-a-quote'
    | '/search'
    | '/shop'
    | '/shop-by-project'
    | '/category/$slug'
    | '/product/$slug'
    | '/project/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BusinessAccountRoute: typeof BusinessAccountRoute
  CartRoute: typeof CartRoute
  RequestAQuoteRoute: typeof RequestAQuoteRoute
  SearchRoute: typeof SearchRoute
  ShopRoute: typeof ShopRoute
  ShopByProjectRoute: typeof ShopByProjectRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ProductSlugRoute: typeof ProductSlugRoute
  ProjectSlugRoute: typeof ProjectSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop-by-project': {
      id: '/shop-by-project'
      path: '/shop-by-project'
      fullPath: '/shop-by-project'
      preLoaderRoute: typeof ShopByProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-a-quote': {
      id: '/request-a-quote'
      path: '/request-a-quote'
      fullPath: '/request-a-quote'
      preLoaderRoute: typeof RequestAQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-account': {
      id: '/business-account'
      path: '/business-account'
      fullPath: '/business-account'
      preLoaderRoute: typeof BusinessAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$slug': {
      id: '/project/$slug'
      path: '/project/$slug'
      fullPath: '/project/$slug'
      preLoaderRoute: typeof ProjectSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BusinessAccountRoute: BusinessAccountRoute,
  CartRoute: CartRoute,
  RequestAQuoteRoute: RequestAQuoteRoute,
  SearchRoute: SearchRoute,
  ShopRoute: ShopRoute,
  ShopByProjectRoute: ShopByProjectRoute,
  CategorySlugRoute: CategorySlugRoute,
  ProductSlugRoute: ProductSlugRoute,
  ProjectSlugRoute: ProjectSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
