-- Autonomous supervisor for the durable Store fulfilment outbox.
create extension if not exists pg_cron;
create extension if not exists pg_net with schema extensions;
create table if not exists public.store_fulfilment_supervisor_runs(id uuid primary key default gen_random_uuid(),started_at timestamptz not null default now(),finished_at timestamptz,recovered_jobs integer not null default 0,dead_lettered_jobs integer not null default 0,pending_jobs integer not null default 0,retry_jobs integer not null default 0,processing_jobs integer not null default 0,dead_letter_jobs integer not null default 0,oldest_actionable_job_at timestamptz,worker_request_id bigint,status text not null default 'running' check(status in('running','healthy','attention','failed')),details jsonb not null default '{}'::jsonb);
alter table public.store_fulfilment_supervisor_runs enable row level security;
drop policy if exists "store fulfilment supervisor admins can read" on public.store_fulfilment_supervisor_runs;
create policy "store fulfilment supervisor admins can read" on public.store_fulfilment_supervisor_runs for select to authenticated using(exists(select 1 from public.organisation_members om where om.organisation_id='00000000-0000-4000-8000-000000000001'::uuid and om.user_id=auth.uid() and om.status='active' and om.role in('owner','admin')) or exists(select 1 from public.user_roles ur where ur.user_id=auth.uid() and ur.role='admin'));
create or replace function public.supervise_store_fulfilment_outbox(p_stale_after interval default interval '10 minutes') returns jsonb language plpgsql security definer set search_path='' as $$ declare vr integer:=0;vd integer:=0;vp integer:=0;vry integer:=0;vpr integer:=0;vdl integer:=0;vo timestamptz;rid uuid;vs text; begin insert into public.store_fulfilment_supervisor_runs default values returning id into rid; update public.store_fulfilment_outbox o set status=case when attempts>=max_attempts then 'dead_letter' else 'retry' end,available_at=case when attempts>=max_attempts then available_at else now() end,locked_at=null,locked_by=null,last_error=left(coalesce(last_error||E'\n','')||'Supervisor recovered abandoned lease',2000),updated_at=now() where status='processing' and locked_at<now()-greatest(p_stale_after,interval '2 minutes');get diagnostics vr=row_count; update public.store_fulfilment_outbox set status='dead_letter',locked_at=null,locked_by=null,updated_at=now() where status in('pending','retry') and attempts>=max_attempts;get diagnostics vd=row_count; select count(*)filter(where status='pending'),count(*)filter(where status='retry'),count(*)filter(where status='processing'),count(*)filter(where status='dead_letter'),min(created_at)filter(where status in('pending','retry') and available_at<=now()) into vp,vry,vpr,vdl,vo from public.store_fulfilment_outbox;vs:=case when vdl>0 or(vo is not null and vo<now()-interval '15 minutes') then 'attention' else 'healthy' end;update public.store_fulfilment_supervisor_runs set finished_at=now(),recovered_jobs=vr,dead_lettered_jobs=vd,pending_jobs=vp,retry_jobs=vry,processing_jobs=vpr,dead_letter_jobs=vdl,oldest_actionable_job_at=vo,status=vs where id=rid;return jsonb_build_object('runId',rid,'status',vs,'recovered',vr,'deadLettered',vd);end $$;
revoke all on function public.supervise_store_fulfilment_outbox(interval) from public,anon,authenticated;
create or replace function public.invoke_store_fulfilment_worker_from_scheduler() returns bigint language plpgsql security definer set search_path='' as $$ declare u text;s text;r bigint;begin select decrypted_secret into u from vault.decrypted_secrets where name='store_fulfilment_worker_url' limit 1;select decrypted_secret into s from vault.decrypted_secrets where name='store_fulfilment_worker_secret' limit 1;if coalesce(u,'')='' or coalesce(s,'')='' then return null;end if;select extensions.http_post(url:=u,headers:=jsonb_build_object('Content-Type','application/json','x-cossa-worker-secret',s),body:=jsonb_build_object('source','pg_cron','scheduledAt',now()),timeout_milliseconds:=10000) into r;return r;end $$;
revoke all on function public.invoke_store_fulfilment_worker_from_scheduler() from public,anon,authenticated;
-- Supervisor is safe to schedule immediately. Worker is scheduled only when both Vault secrets already exist.
do $$ declare j bigint;u text;s text;begin for j in select jobid from cron.job where jobname in('cossa-store-fulfilment-worker','cossa-store-fulfilment-supervisor') loop perform cron.unschedule(j);end loop;perform cron.schedule('cossa-store-fulfilment-supervisor','*/5 * * * *','select public.supervise_store_fulfilment_outbox(interval ''10 minutes'');');select decrypted_secret into u from vault.decrypted_secrets where name='store_fulfilment_worker_url' limit 1;select decrypted_secret into s from vault.decrypted_secrets where name='store_fulfilment_worker_secret' limit 1;if coalesce(u,'')<>'' and coalesce(s,'')<>'' then perform cron.schedule('cossa-store-fulfilment-worker','* * * * *','select public.invoke_store_fulfilment_worker_from_scheduler();');end if;end $$;
